package org.robolectric.annotation.processing.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import java.io.OutputStream
import java.nio.charset.StandardCharsets

// Duplicated in Generator.java (KAPT/javac implementation)
private const val GEN_CLASS = "Shadows"

@Suppress("LongParameterList")
internal fun writeShadowProvider(
  codeGenerator: CodeGenerator,
  dependencies: Dependencies,
  shadowPackage: String,
  shouldInstrumentPackages: Boolean,
  priority: Int,
  shadowInfos: List<ShadowInfo>,
  resetterInfos: List<ResetterInfo>,
) {
  codeGenerator
    .createNewFile(
      dependencies = dependencies,
      packageName = shadowPackage,
      fileName = GEN_CLASS,
      extensionName = "java",
    )
    .use { output ->
      generateShadowProviderContent(
        shadowPackage,
        shouldInstrumentPackages,
        priority,
        shadowInfos,
        resetterInfos,
        output,
      )
    }
}

@Suppress("LongParameterList", "LongMethod")
internal fun generateShadowProviderContent(
  shadowPackage: String,
  shouldInstrumentPackages: Boolean,
  priority: Int,
  shadowInfos: List<ShadowInfo>,
  resetterInfos: List<ResetterInfo>,
  output: OutputStream,
) {
  val shadowsByActual =
    shadowInfos.sortedWith(compareBy(ShadowInfo::actualName, ShadowInfo::shadowBinaryName))
  val (shadowPickers, directShadows) =
    shadowsByActual.partition { it.shadowPickerBinaryName != null }
  val providedPackages =
    if (!shouldInstrumentPackages) {
      emptyList()
    } else {
      shadowedPackages(shadowsByActual.map(ShadowInfo::actualName))
    }

  output.writeText("package $shadowPackage;\n\n")
  output.writeText("import java.util.AbstractMap;\n")
  output.writeText("import java.util.ArrayList;\n")
  output.writeText("import java.util.Collection;\n")
  output.writeText("import java.util.HashMap;\n")
  output.writeText("import java.util.List;\n")
  output.writeText("import java.util.Map;\n")
  output.writeText("import org.robolectric.RuntimeEnvironment;\n")
  output.writeText("import org.robolectric.internal.ShadowProvider;\n\n")
  output.writeText("/** Shadow mapper generated by Robolectric KSP processor. */\n")
  if (priority != 0) {
    output.writeText("@javax.annotation.Priority($priority)\n")
  }
  output.writeText("@SuppressWarnings({\"unchecked\", \"deprecation\"})\n")
  output.writeText("public class $GEN_CLASS implements ShadowProvider {\n")
  output.writeText(
    "  private static final List<Map.Entry<String, String>> SHADOWS = new ArrayList<>(${directShadows.size});\n"
  )
  output.writeText(
    "  private static final Map<String, String> SHADOW_PICKER_MAP = new HashMap<>(${shadowPickers.size});\n\n"
  )
  output.writeText("  static {\n")
  directShadows.forEach { shadowInfo ->
    // ShadowMap resolves providers via Class.getCanonicalName(), so SHADOWS is keyed by the dot
    // name; SHADOW_PICKER_MAP and reset() are keyed by the binary name to match Class.getName().
    val actualCanonicalName = shadowInfo.actualName.replace('$', '.')
    output.writeText(
      "    SHADOWS.add(new AbstractMap.SimpleImmutableEntry<>(" +
        "\"$actualCanonicalName\", \"${shadowInfo.shadowBinaryName}\"));\n"
    )
  }
  shadowPickers.forEach { shadowInfo ->
    output.writeText(
      "    SHADOW_PICKER_MAP.put(\"${shadowInfo.actualName}\", \"${shadowInfo.shadowPickerBinaryName}\");\n"
    )
  }
  output.writeText("  }\n\n")

  writeShadowOfMethods(shadowsByActual, output)

  output.writeText("  @Override\n")
  output.writeText("  public void reset(org.robolectric.internal.ClassTracker classTracker) {\n")
  resetterInfos.forEach { resetter ->
    val sdkGuard =
      when {
        resetter.minSdk != -1 && resetter.maxSdk != -1 ->
          "if (RuntimeEnvironment.getApiLevel() >= ${resetter.minSdk} " +
            "&& RuntimeEnvironment.getApiLevel() <= ${resetter.maxSdk}) "
        resetter.minSdk != -1 -> "if (RuntimeEnvironment.getApiLevel() >= ${resetter.minSdk}) "
        resetter.maxSdk != -1 -> "if (RuntimeEnvironment.getApiLevel() <= ${resetter.maxSdk}) "
        else -> ""
      }
    output.writeText(
      "    if (classTracker.isClassLoaded(\"${resetter.shadowClassName}\") " +
        "|| classTracker.isClassLoaded(\"${resetter.actualBinaryName}\")) {\n"
    )
    output.writeText("      $sdkGuard${resetter.methodCall}\n")
    output.writeText("    }\n")
  }
  output.writeText("  }\n\n")

  output.writeText("  @Override\n")
  output.writeText("  public Collection<Map.Entry<String, String>> getShadows() {\n")
  output.writeText("    return SHADOWS;\n")
  output.writeText("  }\n\n")

  output.writeText("  @Override\n")
  output.writeText("  public String[] getProvidedPackageNames() {\n")
  if (providedPackages.isEmpty()) {
    output.writeText("    return new String[] {};\n")
  } else {
    output.writeText("    return new String[] {\n")
    providedPackages.forEachIndexed { index, packageName ->
      val suffix = if (index == providedPackages.lastIndex) "" else ","
      output.writeText("      \"$packageName\"$suffix\n")
    }
    output.writeText("    };\n")
  }
  output.writeText("  }\n\n")

  output.writeText("  @Override\n")
  output.writeText("  public Map<String, String> getShadowPickerMap() {\n")
  output.writeText("    return SHADOW_PICKER_MAP;\n")
  output.writeText("  }\n")
  output.writeText("}\n")
}

/**
 * Emits `shadowOf()` helpers for SDK-visible shadows whose actual class is public, mirroring the
 * javac processor. Generic types are emitted in raw form.
 */
private fun writeShadowOfMethods(shadowsByActual: List<ShadowInfo>, output: OutputStream) {
  shadowsByActual
    .filter { it.isInAndroidSdk && it.actualIsPublic }
    .distinctBy { it.actualName }
    .forEach { shadowInfo ->
      val actualType = shadowInfo.actualName.replace('$', '.')
      val shadowType = shadowInfo.shadowBinaryName.replace('$', '.')
      output.writeText("  public static $shadowType shadowOf($actualType actual) {\n")
      output.writeText("    return org.robolectric.shadow.api.Shadow.extract(actual);\n")
      output.writeText("  }\n\n")
    }
}

internal fun writeServiceFile(
  codeGenerator: CodeGenerator,
  dependencies: Dependencies,
  shadowPackage: String,
) {
  codeGenerator
    .createNewFileByPath(
      dependencies = dependencies,
      path = "META-INF/services/org.robolectric.internal.ShadowProvider",
      extensionName = "",
    )
    .use { output -> output.writeText(generateServiceFileContent(shadowPackage)) }
}

/**
 * Java packages to advertise for instrumentation: the package of every shadowed class, excluding
 * `org.robolectric.*`, with redundant sub-packages collapsed (e.g. `android.os.storage` is dropped
 * when `android.os` is present). Mirrors `RobolectricModel.getShadowedPackages()`.
 */
internal fun shadowedPackages(actualNames: List<String>): List<String> {
  val sorted =
    actualNames
      .mapNotNull { it.substringBeforeLast('.', missingDelimiterValue = "").ifBlank { null } }
      .filterNot { it == "org.robolectric" || it.startsWith("org.robolectric.") }
      .distinct()
      .sorted()
  val collapsed = mutableListOf<String>()
  for (packageName in sorted) {
    val parent = collapsed.lastOrNull()
    if (parent == null || !packageName.startsWith("$parent.")) {
      collapsed.add(packageName)
    }
  }
  return collapsed
}

internal fun generateServiceFileContent(shadowPackage: String): String =
  "$shadowPackage.$GEN_CLASS\n"

private fun OutputStream.writeText(value: String) {
  write(value.toByteArray(StandardCharsets.UTF_8))
}
