/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.robolectric.lib3;

public final class R {
    public static final class attr {
    }
    public static final class raw {
        public static int lib_raw_resource=0x7f020000;
        public static int lib_raw_resource_from_3=0x7f020001;
    }
    public static final class string {
        public static int in_all_libs=0x7f030001;
        public static int in_lib1_and_lib3=0x7f030002;
        public static int in_lib2_and_lib3=0x7f030003;
        public static int only_in_lib3=0x7f030000;
    }
}
