/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.xtremelabs.droidsugar;

public final class R {
    private static int nextId = 0;

    public static final class id {
        public static final int media_time = nextId++;
        public static final int media_title = nextId++;
        public static final int media_subtitle = nextId++;
    }
}
