/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.xtremelabs.droidsugar;

public final class R {
    private static int nextId = 0;

    public static final class id {
        public static final int time = nextId++;
        public static final int title = nextId++;
        public static final int subtitle = nextId++;
        public static final int snippet_text = nextId++;
        public static final int include_id = nextId++;
        public static final int inner_text = nextId++;
        public static final int map_view = nextId++;
    }

    public static final class string {
        public static final int howdy = nextId++;
        public static final int hello = nextId++;
    }
    
    public static final class array {
        public static final int items = nextId++;
    }
}
