package org.robolectric.gradle

import java.io.File
import java.util.Properties
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.FileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.TaskProvider

abstract class ProvideBuildClasspathTask : DefaultTask() {
  @get:Input abstract val sdkCoordinates: ListProperty<String>
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.NONE)
  abstract val sdkFiles: ListProperty<FileCollection>

  @get:OutputFile abstract val outFile: RegularFileProperty

  @TaskAction
  @Throws(Exception::class)
  fun writeProperties() {
    val props = Properties()
    val sdkCoordinates = sdkCoordinates.get()
    val sdkFiles = sdkFiles.get()

    sdkCoordinates.forEachIndexed { index, coordinates ->
      props.setProperty(coordinates, sdkFiles[index].files.joinToString(File.pathSeparator))
    }

    val outFile = outFile.get().asFile
    val outDir = outFile.parentFile
    if (!outDir.isDirectory) {
      outDir.mkdirs()
    }

    outFile.printWriter().use { out -> props.store(out, "# GENERATED by $this -- do not edit") }
  }

  internal companion object {
    private const val PREINSTRUMENTED_KEY = "robolectric.usePreinstrumentedJars"

    internal fun configure(
      project: Project,
      taskProvider: TaskProvider<ProvideBuildClasspathTask>,
    ) {
      taskProvider.configure {
        val usePreinstrumentedJars =
          project.providers
            .systemProperty(PREINSTRUMENTED_KEY)
            .map { it.toBoolean() }
            .orElse(true)
            .get()

        AndroidSdk.ALL_SDKS.forEach { androidSdk ->
          val coordinates =
            if (usePreinstrumentedJars) androidSdk.preinstrumentedCoordinates
            else androidSdk.coordinates
          val configuration =
            project.configurations.register("sdk${androidSdk.apiLevel}") {
              dependencies.add(project.dependencies.create(coordinates))
            }
          sdkCoordinates.add(coordinates)
          sdkFiles.add(configuration)
        }
      }
    }
  }
}
