package org.robolectric;

import javax.annotation.Generated;

import org.robolectric.internal.ShadowExtractor;
import org.robolectric.util.ShadowProvider;

/**
 * Shadow mapper. Automatically generated by the Robolectric Annotation Processor.
 */
@Generated("org.robolectric.annotation.processing.RobolectricProcessor")
@SuppressWarnings({"unchecked","deprecation"})
public class Shadows implements ShadowProvider {

  public void reset() {
  }
}
