import org.gradle.internal.jvm.Jvm
import org.robolectric.gradle.AndroidSdk

plugins {
  alias(libs.plugins.robolectric.deployed.java.module)
  alias(libs.plugins.robolectric.java.module)
}

abstract class GenerateSdksFileTask : DefaultTask() {
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.ABSOLUTE)
  abstract val sdkFiles: ConfigurableFileCollection

  @get:OutputFile abstract val outFile: RegularFileProperty

  @TaskAction
  fun writeProperties() {
    val outFile = outFile.get().asFile
    val outDir = outFile.parentFile
    if (!outDir.isDirectory) {
      outDir.mkdirs()
    }

    outFile.printWriter().use { out ->
      out.write("# GENERATED by $this -- do not edit\n")

      sdkFiles.files.map { it.absolutePath }.forEach { out.write("$it\n") }
    }
  }
}

val processorSdkConfigurations =
  AndroidSdk.ALL_SDKS.map { androidSdk ->
    configurations.register("processorSdk${androidSdk.apiLevel}") {
      isCanBeConsumed = false
      isCanBeResolved = true

      dependencies.add(project.dependencies.create(androidSdk.coordinates))
    }
  }

val generateSdksFile =
  tasks.register<GenerateSdksFileTask>("generateSdksFile") {
    outFile = project.layout.buildDirectory.file("sdks.txt")
    processorSdkConfigurations.forEach(sdkFiles::from)
  }

tasks.classes.configure { dependsOn(generateSdksFile) }

dependencies {
  api(project(":annotations"))
  api(project(":shadowapi"))

  compileOnly(libs.findbugs.jsr305)
  api(libs.asm)
  api(libs.asm.util)
  api(libs.guava)
  api(libs.gson)
  implementation(libs.auto.common)

  val toolsJar: File? = Jvm.current().getToolsJar()
  toolsJar?.let { implementation(files(it)) }

  testImplementation(libs.junit4)
  testImplementation(libs.mockito)
  testImplementation(libs.mockito.subclass)
  testImplementation(libs.compile.testing)
  testImplementation(libs.truth)
}
