package org.robolectric.annotation.processing.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import java.io.OutputStream
import java.nio.charset.StandardCharsets

// Duplicated in Generator.java (KAPT/javac implementation)
private const val GEN_CLASS = "Shadows"

@Suppress("LongParameterList")
internal fun writeShadowProvider(
  codeGenerator: CodeGenerator,
  dependencies: Dependencies,
  shadowPackage: String,
  shouldInstrumentPackages: Boolean,
  priority: Int,
  shadowInfos: List<ShadowInfo>,
  resetterInfos: List<ResetterInfo>,
) {
  codeGenerator
    .createNewFile(
      dependencies = dependencies,
      packageName = shadowPackage,
      fileName = GEN_CLASS,
      extensionName = "java",
    )
    .use { output ->
      generateShadowProviderContent(
        shadowPackage,
        shouldInstrumentPackages,
        priority,
        shadowInfos,
        resetterInfos,
        output,
      )
    }
}

@Suppress("LongParameterList", "LongMethod")
internal fun generateShadowProviderContent(
  shadowPackage: String,
  shouldInstrumentPackages: Boolean,
  priority: Int,
  shadowInfos: List<ShadowInfo>,
  resetterInfos: List<ResetterInfo>,
  output: OutputStream,
) {
  val shadowsByActual =
    shadowInfos.sortedWith(compareBy(ShadowInfo::actualName, ShadowInfo::shadowBinaryName))
  val shadowPickers = shadowsByActual.filter { it.shadowPickerBinaryName != null }
  val directShadows = shadowsByActual.filter { it.shadowPickerBinaryName == null }
  val providedPackages =
    if (!shouldInstrumentPackages) {
      emptyList()
    } else {
      directShadows
        .mapNotNull {
          it.actualName.substringBeforeLast('.', missingDelimiterValue = "").ifBlank { null }
        }
        .distinct()
        .sorted()
    }

  output.writeText("package $shadowPackage;\n\n")
  output.writeText("import java.util.AbstractMap;\n")
  output.writeText("import java.util.ArrayList;\n")
  output.writeText("import java.util.Collection;\n")
  output.writeText("import java.util.HashMap;\n")
  output.writeText("import java.util.List;\n")
  output.writeText("import java.util.Map;\n")
  output.writeText("import org.robolectric.RuntimeEnvironment;\n")
  output.writeText("import org.robolectric.internal.ShadowProvider;\n\n")
  output.writeText("/** Shadow mapper generated by Robolectric KSP processor. */\n")
  if (priority != 0) {
    output.writeText("@javax.annotation.Priority($priority)\n")
  }
  output.writeText("@SuppressWarnings({\"unchecked\", \"deprecation\"})\n")
  output.writeText("public class $GEN_CLASS implements ShadowProvider {\n")
  output.writeText(
    "  private static final List<Map.Entry<String, String>> SHADOWS = new ArrayList<>(${directShadows.size});\n"
  )
  output.writeText(
    "  private static final Map<String, String> SHADOW_PICKER_MAP = new HashMap<>(${shadowPickers.size});\n\n"
  )
  output.writeText("  static {\n")
  directShadows.forEach { shadowInfo ->
    val entryLine =
      "    SHADOWS.add(new AbstractMap.SimpleImmutableEntry<>(" +
        "\"${shadowInfo.actualName}\", \"${shadowInfo.shadowBinaryName}\"));\n"
    output.writeText(entryLine)
  }
  shadowPickers.forEach { shadowInfo ->
    output.writeText(
      "    SHADOW_PICKER_MAP.put(\"${shadowInfo.actualName}\", \"${shadowInfo.shadowPickerBinaryName}\");\n"
    )
  }
  output.writeText("  }\n\n")

  output.writeText("  @Override\n")
  output.writeText("  public void reset() {\n")
  resetterInfos.forEach { resetter ->
    val guard =
      when {
        resetter.minSdk != -1 && resetter.maxSdk != -1 ->
          "if (RuntimeEnvironment.getApiLevel() >= ${resetter.minSdk} " +
            "&& RuntimeEnvironment.getApiLevel() <= ${resetter.maxSdk}) "
        resetter.minSdk != -1 -> "if (RuntimeEnvironment.getApiLevel() >= ${resetter.minSdk}) "
        resetter.maxSdk != -1 -> "if (RuntimeEnvironment.getApiLevel() <= ${resetter.maxSdk}) "
        else -> ""
      }
    output.writeText("    $guard${resetter.methodCall}\n")
  }
  output.writeText("  }\n\n")

  output.writeText("  @Override\n")
  output.writeText("  public Collection<Map.Entry<String, String>> getShadows() {\n")
  output.writeText("    return SHADOWS;\n")
  output.writeText("  }\n\n")

  output.writeText("  @Override\n")
  output.writeText("  public String[] getProvidedPackageNames() {\n")
  if (providedPackages.isEmpty()) {
    output.writeText("    return new String[] {};\n")
  } else {
    output.writeText("    return new String[] {\n")
    providedPackages.forEachIndexed { index, packageName ->
      val suffix = if (index == providedPackages.lastIndex) "" else ","
      output.writeText("      \"$packageName\"$suffix\n")
    }
    output.writeText("    };\n")
  }
  output.writeText("  }\n\n")

  output.writeText("  @Override\n")
  output.writeText("  public Map<String, String> getShadowPickerMap() {\n")
  output.writeText("    return SHADOW_PICKER_MAP;\n")
  output.writeText("  }\n")
  output.writeText("}\n")
}

internal fun writeServiceFile(
  codeGenerator: CodeGenerator,
  dependencies: Dependencies,
  shadowPackage: String,
) {
  codeGenerator
    .createNewFileByPath(
      dependencies = dependencies,
      path = "META-INF/services/org.robolectric.internal.ShadowProvider",
      extensionName = "",
    )
    .use { output -> output.writeText(generateServiceFileContent(shadowPackage)) }
}

internal fun generateServiceFileContent(shadowPackage: String): String =
  "$shadowPackage.$GEN_CLASS\n"

private fun OutputStream.writeText(value: String) {
  write(value.toByteArray(StandardCharsets.UTF_8))
}
