/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.robolectric.lib2;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int attrFromLib2=0x7f010000;
    }
    public static final class raw {
        public static int lib_raw_resource=0x7f020000;
        public static int lib_raw_resource_from_2=0x7f020001;
    }
    public static final class string {
        public static int in_all_libs=0x7f030001;
        public static int in_lib2_and_lib3=0x7f030002;
        public static int only_in_lib2=0x7f030000;
    }
    public static final class styleable {
        /** Attributes that can be used with a CustomView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CustomView_attrFromLib2 org.robolectric.lib2:attrFromLib2}</code></td><td></td></tr>
           </table>
           @see #CustomView_attrFromLib2
         */
        public static final int[] CustomView = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link org.robolectric.lib2.R.attr#attrFromLib2}
          attribute's value can be found in the {@link #CustomView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.robolectric.lib2:attrFromLib2
        */
        public static int CustomView_attrFromLib2 = 0;
    };
}
