/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.xtremelabs.robolectric;

public final class R {
    private static int nextId = 1234;

    public static final class id {
        public static final int time = nextId++;
        public static final int title = nextId++;
        public static final int subtitle = nextId++;
        public static final int snippet_text = nextId++;
        public static final int include_id = nextId++;
        public static final int inner_text = nextId++;
        public static final int map_view = nextId++;
        public static final int true_checkbox = nextId++;
        public static final int false_checkbox = nextId++;
        public static final int default_checkbox = nextId++;
        public static final int image = nextId++;
        public static final int edit_text = nextId++;
        public static final int edit_text2 = nextId++;
        public static final int outer_merge = nextId++;
        public static final int web_view = nextId++;
    }

    public static final class string {
        public static final int howdy = nextId++;
        public static final int hello = nextId++;
        public static final int some_html = nextId++;
        public static final int greeting = nextId++;
    }

    public static final class array {
        public static final int items = nextId++;
        public static final int greetings = nextId++;
    }

    public static final class color {
        public static final int background = nextId++;
        public static final int foreground = nextId++;
        public static final int grey42 = nextId++;
        public static final int black = nextId++;
        public static final int white = nextId++;
        public static final int clear = nextId++;
        public static final int color_with_alpha = nextId++;
        public static final int android_namespaced_black = nextId++;
        public static final int android_red = nextId++;
    }

    public static final class drawable {
        public static final int an_image = nextId++;
        public static final int an_other_image = nextId++;
        public static final int third_image = nextId++;
        public static final int fourth_image = nextId++;
        public static final int image_background = nextId++;
    }

    public static final class layout {
        public static final int main = nextId++;
        public static final int media = nextId++;
        public static final int inner_merge = nextId++;
    }

    public static final class raw {
        public static final int raw_resource = nextId++;
        public static final int raw_no_ext = nextId++;
    }

    public static final class menu {
        public static final int test = nextId++;
    }

}
