/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.xtremelabs.robolectric;

public final class R {
    private static int nextId = 1234;

    public static final class id {
        public static final int time = nextId++;
        public static final int title = nextId++;
        public static final int subtitle = nextId++;
        public static final int snippet_text = nextId++;
        public static final int include_id = nextId++;
        public static final int inner_text = nextId++;
        public static final int map_view = nextId++;
        public static final int true_checkbox = nextId++;
        public static final int false_checkbox = nextId++;
        public static final int default_checkbox = nextId++;
        public static final int image = nextId++;
        public static final int icon = nextId++;
        public static final int text1 = nextId++;
        public static final int button = nextId++;
        public static final int invalid_onclick_button = nextId++;
        public static final int edit_text = nextId++;
        public static final int edit_text2 = nextId++;
        public static final int outer_merge = nextId++;
        public static final int web_view = nextId++;

        public static final int black_text_view = nextId++;
        public static final int white_text_view = nextId++;
        public static final int grey_text_view = nextId++;

        public static final int black_text_view_hint = nextId++;
        public static final int white_text_view_hint = nextId++;
        public static final int grey_text_view_hint = nextId++;

        public static final int textStyle = nextId++;
        public static final int textStyle2 = nextId++;
        public static final int textStyle3 = nextId++;

        public static final int test_menu_1 = nextId++;
        public static final int test_menu_2 = nextId++;
        public static final int test_menu_3 = nextId++;

        public static final int group_id_1 = nextId++;

        public static final int test_submenu_1 = nextId++;

        public static final int fragment = nextId++;
        public static final int dynamic_fragment_container = nextId++;
        public static final int content_view = nextId++;
    }

    public static final class string {
        public static final int howdy = nextId++;
        public static final int hello = nextId++;
        public static final int some_html = nextId++;
        public static final int greeting = nextId++;
        public static final int copy = nextId++;
    }

    public static final class plurals {
        public static final int beer = nextId++;
    }

    public static final class array {
        public static final int items = nextId++;
        public static final int greetings = nextId++;
        public static final int alertDialogTestItems = nextId++;
        public static final int emailAddressTypes = nextId++;
        public static final int zero_to_four_int_array = nextId++;
        public static final int empty_int_array = nextId++;
        public static final int with_references_int_array = nextId++;
    }

    public static final class color {
        public static final int background = nextId++;
        public static final int foreground = nextId++;
        public static final int grey42 = nextId++;
        public static final int black = nextId++;
        public static final int white = nextId++;
        public static final int clear = nextId++;
        public static final int color_with_alpha = nextId++;
        public static final int android_namespaced_black = nextId++;
        public static final int android_red = nextId++;
    }

    public static final class drawable {
        public static final int an_image = nextId++;
        public static final int an_other_image = nextId++;
        public static final int third_image = nextId++;
        public static final int fourth_image = nextId++;
        public static final int image_background = nextId++;
        public static final int l0_red = nextId++;
        public static final int l1_orange = nextId++;
        public static final int l2_yellow = nextId++;
        public static final int l3_green = nextId++;
        public static final int l4_blue = nextId++;
        public static final int l5_indigo = nextId++;
        public static final int l6_violet = nextId++;
        public static final int l7_white = nextId++;
        public static final int rainbow = nextId++;
        public static final int state_drawable = nextId++;
        public static final int animation_list = nextId++;
        public static final int nine_patch_drawable = nextId++;
    }

    public static final class layout {
        public static final int main = nextId++;
        public static final int media = nextId++;
        public static final int inner_merge = nextId++;
        public static final int included_linear_layout = nextId++;
        public static final int with_invalid_onclick = nextId++;
        public static final int text_views = nextId++;
        public static final int text_views_hints = nextId++;
        public static final int toplevel_merge = nextId++;
        public static final int tab_activity = nextId++;
        public static final int different_screen_sizes = nextId++;
        public static final int fragment_activity = nextId++;
    }

    public static final class raw {
        public static final int raw_resource = nextId++;
        public static final int raw_no_ext = nextId++;
    }

    public static final class menu {
        public static final int test = nextId++;
        public static final int test_withchilds = nextId++;
    }

    public static final class xml {
        public static final int preferences = nextId++;
    }

    public static final class styleable {
        public static final int[] TitleBar = {id.textStyle};
        public static final int TitleBar_textStyle = 0;

        public static final int[] HeaderBar = {id.textStyle2, id.textStyle3};
        public static final int HeaderBar_textStyle2 = 0;
        public static final int HeaderBar_textStyle3 = 1;
    }

    public static final class dimen {
        public static final int test_dp_dimen = nextId++;
        public static final int test_dip_dimen = nextId++;
        public static final int test_pt_dimen = nextId++;
        public static final int test_px_dimen = nextId++;
        public static final int test_sp_dimen = nextId++;
    }

    public static final class integer {
        public static final int test_non_integer = nextId++;
        public static final int test_integer1 = nextId++;
        public static final int test_integer2 = nextId++;
        public static final int test_large_hex = nextId++;
    }
    
    public static final class bool {
    	public static final int false_bool_value = nextId++;
    	public static final int true_bool_value = nextId++;
    	public static final int zero_is_false = nextId++;
    	public static final int integers_are_true = nextId++;
    }
}
