package org.robolectric;
import com.example.objects.AnyObject;
import com.example.objects.innerpackage.InnerPackageDummy;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import org.robolectric.annotation.processing.shadows.ShadowClassNameOnly;
import org.robolectric.annotation.processing.shadows.ShadowDummy;
import org.robolectric.annotation.processing.shadows.ShadowDummy2;
import org.robolectric.annotation.processing.shadows.ShadowInnerPackageDummy;
import org.robolectric.internal.ShadowProvider;
import org.robolectric.shadow.api.Shadow;

/**
 * Shadow mapper. Automatically generated by the Robolectric Annotation Processor.
 */
@Generated("org.robolectric.annotation.processing.RobolectricProcessor")
@SuppressWarnings({"unchecked","deprecation"})
public class Shadows implements ShadowProvider {
  private static final List<Map.Entry<String, String>> SHADOWS = new ArrayList<>(4);

  static {
    SHADOWS.add(new AbstractMap.SimpleImmutableEntry<>("com.example.objects.AnyObject", "org.robolectric.annotation.processing.shadows.ShadowClassNameOnly"));
    SHADOWS.add(new AbstractMap.SimpleImmutableEntry<>("com.example.objects.Dummy", "org.robolectric.annotation.processing.shadows.ShadowDummy"));
    SHADOWS.add(new AbstractMap.SimpleImmutableEntry<>("org.example.objects.Dummy", "org.robolectric.annotation.processing.shadows.ShadowDummy2"));
    SHADOWS.add(new AbstractMap.SimpleImmutableEntry<>("com.example.objects.innerpackage.InnerPackageDummy", "org.robolectric.annotation.processing.shadows.ShadowInnerPackageDummy"));
  }

  public static ShadowClassNameOnly shadowOf(AnyObject actual) {
    return (ShadowClassNameOnly) Shadow.extract(actual);
  }

  public static ShadowDummy shadowOf(com.example.objects.Dummy actual) {
    return (ShadowDummy) Shadow.extract(actual);
  }

  public static ShadowDummy2 shadowOf(org.example.objects.Dummy actual) {
    return (ShadowDummy2) Shadow.extract(actual);
  }

  public static ShadowInnerPackageDummy shadowOf(InnerPackageDummy actual) {
    return (ShadowInnerPackageDummy) Shadow.extract(actual);
  }

  @Override
  public void reset() {
    ShadowClassNameOnly.anotherResetter();
    ShadowDummy.resetter_method();
  }

  @Override
  public Collection<Map.Entry<String, String>> getShadows() {
    return SHADOWS;
  }

  @Override
  public String[] getProvidedPackageNames() {
    return new String[] {
        "com.example.objects",
        "org.example.objects"
    };
  }

}