/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.robolectric.shadows.androidx.fragment;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int burritos=0x7f030002;
        public static final int custom_activity_view=0x7f030000;
        public static final int tacos=0x7f030001;
    }
    public static final class layout {
        public static final int custom_activity_view=0x7f020000;
        public static final int fragment_contents=0x7f020001;
    }
}
