/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.robolectric.lib1;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int attr2FromLib1=0x7f010001;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int attrFromLib1=0x7f010000;
    }
    public static final class string {
        public static int in_all_libs=0x7f020001;
        public static int in_lib1_and_lib3=0x7f020003;
        public static int in_main_and_lib1=0x7f020002;
        public static int only_in_lib1=0x7f020000;
    }
    public static final class styleable {
        /** Attributes that can be used with a Lib1Styleable.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #Lib1Styleable_attr2FromLib1 org.robolectric.lib1:attr2FromLib1}</code></td><td></td></tr>
           <tr><td><code>{@link #Lib1Styleable_attrFromLib1 org.robolectric.lib1:attrFromLib1}</code></td><td></td></tr>
           </table>
           @see #Lib1Styleable_attr2FromLib1
           @see #Lib1Styleable_attrFromLib1
         */
        public static final int[] Lib1Styleable = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link org.robolectric.lib1.R.attr#attr2FromLib1}
          attribute's value can be found in the {@link #Lib1Styleable} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.robolectric.lib1:attr2FromLib1
        */
        public static int Lib1Styleable_attr2FromLib1 = 1;
        /**
          <p>This symbol is the offset where the {@link org.robolectric.lib1.R.attr#attrFromLib1}
          attribute's value can be found in the {@link #Lib1Styleable} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.robolectric.lib1:attrFromLib1
        */
        public static int Lib1Styleable_attrFromLib1 = 0;
    };
}
