/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.robolectric;

public final class R {
  /* To regenerate ids, run this ruby script:

    path_to_r = "/path/to/src/test/java/org/robolectric/R.java"

    if path_to_r =~ /^\/path\/to/
      raise "please change the path to this file!"
    else
      original_contents = File.read(path_to_r)
      x = 0xffff
      new_contents = original_contents.gsub(/class|0x[0-9a-fA-F]+;/) do |match|
      if match == "class"
        x += 0x100
        x = x & 0xffffff00
        x -= 1
        "class"
      else
        "0x#{"%x" % (x += 1)};"
      end
      end
      File.open(path_to_r, "w") { |f| f << new_contents }
    end

   */


  public static final class id {
    public static final int time = 0x10000;
    public static final int title = 0x10001;
    public static final int subtitle = 0x10002;
    public static final int snippet_text = 0x10003;
    public static final int include_id = 0x10004;
    public static final int inner_text = 0x10005;
    public static final int map_view = 0x10006;
    public static final int true_checkbox = 0x10007;
    public static final int false_checkbox = 0x10008;
    public static final int default_checkbox = 0x10009;
    public static final int image = 0x1000a;
    public static final int icon = 0x1000b;
    public static final int text1 = 0x1000c;
    public static final int button = 0x1000d;
    public static final int invalid_onclick_button = 0x1000e;
    public static final int edit_text = 0x1000f;
    public static final int edit_text2 = 0x10010;
    public static final int outer_merge = 0x10011;
    public static final int web_view = 0x10012;

    public static final int black_text_view = 0x10013;
    public static final int white_text_view = 0x10014;
    public static final int grey_text_view = 0x10015;

    public static final int black_text_view_hint = 0x10016;
    public static final int white_text_view_hint = 0x10017;
    public static final int grey_text_view_hint = 0x10018;

    public static final int textStyle = 0x10019;
    public static final int textStyle2 = 0x1001a;
    public static final int textStyle3 = 0x1001b;

    public static final int test_menu_1 = 0x1001c;
    public static final int test_menu_2 = 0x1001d;
    public static final int test_menu_3 = 0x1001e;

    public static final int group_id_1 = 0x1001f;

    public static final int test_submenu_1 = 0x10020;

    public static final int fragment = 0x10021;
    public static final int dynamic_fragment_container = 0x10022;
    public static final int content_view = 0x10023;

    public static final int portrait = 0x10024;
    public static final int landscape = 0x10025;
    public static final int tacos = 0x10026;
    public static final int burritos = 0x10027;
    public static final int lam_container = 0x10028;
    public static final int lam_inner_contents = 0x10029;
    public static final int my_fragment = 0x1002a;
    public static final int my_landscape_text = 0x1002b;

    public static final int itemType = 0x1002c;
    public static final int scrollBars = 0x1002d;
    public static final int keycode = 0x1002e;
    public static final int aspectRatio = 0x1002f;
    public static final int aspectRatioEnabled = 0x10030;

    public static final int marsupial = 0x10031;
    public static final int ungulate = 0x10032;

    public static final int custom_view = 0x10033;

    public static final int custom_title_text = 0x10034;
  }

  public static final class string {
    public static final int howdy = 0x10100;
    public static final int hello = 0x10101;
    public static final int some_html = 0x10102;
    public static final int greeting = 0x10103;
    public static final int copy = 0x10104;
    public static final int ok = 0x10105;
    public static final int ok2 = 0x10106;
    public static final int only_in_main = 0x10107;
    public static final int only_in_lib1 = 0x10108;
    public static final int only_in_lib2 = 0x10109;
    public static final int only_in_lib3 = 0x1010a;
    public static final int in_all_libs = 0x1010b;
    public static final int in_lib2_and_lib3 = 0x1010c;
    public static final int in_lib1_and_lib3 = 0x1010d;
    public static final int in_main_and_lib1 = 0x1010e;
    public static final int interpolate = 0x1010f;
  }

  public static final class plurals {
    public static final int beer = 0x10200;
  }

  public static final class array {
    public static final int items = 0x10300;
    public static final int greetings = 0x10301;
    public static final int alertDialogTestItems = 0x10302;
    public static final int emailAddressTypes = 0x10303;
    public static final int zero_to_four_int_array = 0x10304;
    public static final int empty_int_array = 0x10305;
    public static final int with_references_int_array = 0x10306;
  }

  public static final class color {
    public static final int background = 0x10400;
    public static final int foreground = 0x10401;
    public static final int grey42 = 0x10402;
    public static final int black = 0x10403;
    public static final int white = 0x10404;
    public static final int clear = 0x10405;
    public static final int color_with_alpha = 0x10406;
    public static final int android_namespaced_black = 0x10407;
    public static final int android_namespaced_transparent = 0x10408;
    public static final int android_red = 0x10409;
    public static final int test_color_1 = 0x1040a;
    public static final int color_state_list = 0x1040b;
    public static final int list_separator = 0x1040c;
  }

  public static final class drawable {
    public static final int an_image = 0x10500;
    public static final int an_other_image = 0x10501;
    public static final int third_image = 0x10502;
    public static final int fourth_image = 0x10503;
    public static final int image_background = 0x10504;
    public static final int l0_red = 0x10505;
    public static final int l1_orange = 0x10506;
    public static final int l2_yellow = 0x10507;
    public static final int l3_green = 0x10508;
    public static final int l4_blue = 0x10509;
    public static final int l5_indigo = 0x1050a;
    public static final int l6_violet = 0x1050b;
    public static final int l7_white = 0x1050c;
    public static final int rainbow = 0x1050d;
    public static final int state_drawable = 0x1050e;
    public static final int nine_patch_drawable = 0x1050f;
    public static final int drawable_with_nine_patch = 0x10510;
  }

  public static final class layout {
    public static final int activity_list_item = 0x10600;
    public static final int custom_layout = 0x10601;
    public static final int custom_layout2 = 0x10602;
    public static final int custom_layout3 = 0x10603;
    public static final int custom_layout4 = 0x10604;
    public static final int different_screen_sizes = 0x10605;
    public static final int edit_text = 0x10606;
    public static final int fragment = 0x10607;
    public static final int fragment_activity = 0x10608;
    public static final int fragment_contents = 0x10609;
    public static final int included_layout_parent = 0x1060a;
    public static final int included_linear_layout = 0x1060b;
    public static final int inner_merge = 0x1060c;
    public static final int lam_inner = 0x1060d;
    public static final int lam_outer = 0x1060e;
    public static final int main = 0x1060f;
    public static final int mapview = 0x10610;
    public static final int media = 0x10611;
    public static final int multi_orientation = 0x10612;
    public static final int outer = 0x10613;
    public static final int override_include = 0x10614;
    public static final int request_focus = 0x10615;
    public static final int request_focus_with_two_edit_texts = 0x10616;
    public static final int snippet = 0x10617;
    public static final int styles_button_layout = 0x10618;
    public static final int tab_activity = 0x10619;
    public static final int text_views = 0x1061a;
    public static final int text_views_hints = 0x1061b;
    public static final int toplevel_merge = 0x1061c;
    public static final int webview_holder = 0x1061d;
    public static final int with_invalid_onclick = 0x1061e;
    public static final int styles_button_with_style_layout = 0x1061f;
    public static final int activity_fragment = 0x10620;
    public static final int custom_title = 0x10621;
  }

  public static final class anim {
    public static final int test_anim_1 = 0x10700;
    public static final int animation_list = 0x10701;
  }

  public static final class animator {
    public static final int spinning = 0x10710;
  }

  public static final class raw {
    public static final int raw_resource = 0x10800;
    public static final int raw_no_ext = 0x10801;
    public static final int lib_raw_resource = 0x10802;
  }

  public static final class attr {
    public static final int isSugary = 0x10900;
    public static final int itemType = 0x10901;
    public static final int scrollBars = 0x10902;
    public static final int gravity = 0x10903;
    public static final int keycode = 0x10904;
    public static final int aspectRatio = 0x10905;
    public static final int aspectRatioEnabled = 0x10906;
    public static final int items = 0x10907;
    public static final int logoHeight = 0x10908;
    public static final int quitKeyCombo = 0x10909;
    public static final int responses = 0x1090a;
    public static final int animalStyle = 0x1090b;
  }

  public static final class menu {
    public static final int test = 0x10a00;
    public static final int test_withchilds = 0x10a01;
    public static final int action_menu = 0x10a02;
  }

  public static final class xml {
    public static final int preferences = 0x10b00;
  }

  public static final class styleable {
    public static final int[] CustomView = {
        attr.itemType,
        attr.scrollBars,
        attr.keycode,
        attr.aspectRatio,
        attr.aspectRatioEnabled,
        attr.quitKeyCombo,
        attr.animalStyle
    };

    public static final int CustomView_itemType = 0;
    public static final int CustomView_scrollBars = 1;
    public static final int CustomView_keycode = 2;
    public static final int CustomView_aspectRatio = 3;
    public static final int CustomView_aspectRatioEnabled = 4;
    public static final int CustomView_quitKeyCombo = 5;
    public static final int CustomView_animalStyle = 6;

    public static final int[] HeaderBar = {id.textStyle2, id.textStyle3};
    public static final int HeaderBar_textStyle2 = 0;
    public static final int HeaderBar_textStyle3 = 1;
  }

  public static final class dimen {
    public static final int test_dp_dimen = 0x10c00;
    public static final int test_dip_dimen = 0x10c01;
    public static final int test_pt_dimen = 0x10c02;
    public static final int test_px_dimen = 0x10c03;
    public static final int test_sp_dimen = 0x10c04;
    public static final int test_in_dimen = 0x10c05;
    public static final int test_mm_dimen = 0x10c06;
  }

  public static final class integer {
    public static final int test_non_integer = 0x10d00;
    public static final int test_integer1 = 0x10d01;
    public static final int test_integer2 = 0x10d02;
    public static final int test_large_hex = 0x10d03;
    public static final int meaning_of_life = 0x10d04;
    public static final int loneliest_number = 0x10d05;
    public static final int there_can_be_only = 0x10d06;
    public static final int hex_int = 0x10d07;
    public static final int test_value_with_zero = 0x10d08;
    public static final int reference_to_meaning_of_life = 0x10d09;
  }

  public static final class bool {
    public static final int false_bool_value = 0x10e00;
    public static final int true_bool_value = 0x10e01;
    public static final int zero_is_false = 0x10e02;
    public static final int integers_are_true = 0x10e03;
    public static final int reference_to_true = 0x10e04;
  }

  public static final class style {
    public static final int FancyStyle = 0x10f00;
    public static final int Theme_Robolectric = 0x10f01;
    public static final int Theme_AnotherTheme = 0x10f02;
    public static final int MyCustomView = 0x10f03;
    public static final int Widget_Robolectric_Button = 0x10f04;
    public static final int Widget_AnotherTheme_Button = 0x10f05;
    public static final int Sized = 0x10f06;
    public static final int Gastropod = 0x10f07;
    public static final int Theme_ThirdTheme = 0x10f08;
  }
}
