/*
 * AUTO-GENERATED - DO NOT MODIFY.
 *
 * This file was generated by the 'build-resources.rb' file in /scripts.
 */
package org.robolectric;

public final class R {
  public static final class id {
    public static final int time = 0x7f000100;
    public static final int title = 0x7f000101;
    public static final int subtitle = 0x7f000102;
    public static final int snippet_text = 0x7f000103;
    public static final int include_id = 0x7f000104;
    public static final int inner_text = 0x7f000105;
    public static final int map_view = 0x7f000106;
    public static final int true_checkbox = 0x7f000107;
    public static final int false_checkbox = 0x7f000108;
    public static final int default_checkbox = 0x7f000109;
    public static final int image = 0x7f00010a;
    public static final int mipmapImage = 0x7f00010b;
    public static final int icon = 0x7f00010c;
    public static final int text1 = 0x7f00010d;
    public static final int button = 0x7f00010e;
    public static final int invalid_onclick_button = 0x7f00010f;
    public static final int edit_text = 0x7f000110;
    public static final int edit_text2 = 0x7f000111;
    public static final int outer_merge = 0x7f000112;
    public static final int web_view = 0x7f000113;

    public static final int black_text_view = 0x7f000114;
    public static final int white_text_view = 0x7f000115;
    public static final int grey_text_view = 0x7f000116;

    public static final int black_text_view_hint = 0x7f000117;
    public static final int white_text_view_hint = 0x7f000118;
    public static final int grey_text_view_hint = 0x7f000119;

    public static final int textStyle = 0x7f00011a;
    public static final int textStyle2 = 0x7f00011b;
    public static final int textStyle3 = 0x7f00011c;

    public static final int test_menu_1 = 0x7f00011d;
    public static final int test_menu_2 = 0x7f00011e;
    public static final int test_menu_3 = 0x7f00011f;

    public static final int group_id_1 = 0x7f000120;

    public static final int test_submenu_1 = 0x7f000121;

    public static final int fragment = 0x7f000122;
    public static final int dynamic_fragment_container = 0x7f000123;
    public static final int content_view = 0x7f000124;

    public static final int portrait = 0x7f000125;
    public static final int landscape = 0x7f000126;
    public static final int tacos = 0x7f000127;
    public static final int burritos = 0x7f000128;
    public static final int lam_container = 0x7f000129;
    public static final int lam_inner_contents = 0x7f00012a;
    public static final int my_fragment = 0x7f00012b;
    public static final int my_landscape_text = 0x7f00012c;

    public static final int itemType = 0x7f00012d;
    public static final int scrollBars = 0x7f00012e;
    public static final int keycode = 0x7f00012f;
    public static final int aspectRatio = 0x7f000130;
    public static final int aspectRatioEnabled = 0x7f000131;

    public static final int marsupial = 0x7f000132;
    public static final int ungulate = 0x7f000133;

    public static final int custom_view = 0x7f000134;

    public static final int custom_title_text = 0x7f000135;

    public static final int remote_view_1 = 0x7f000136;
    public static final int remote_view_2 = 0x7f000137;
    public static final int remote_view_3 = 0x7f000138;

    public static final int hello = 0x7f000139;
    public static final int world = 0x7f00013a;

    public static final int list_view_with_enum_scrollbar = 0x7f00013b;
    public static final int action_search = 0x7f00013c;
  }

  public static final class string {
    public static final int howdy = 0x7f000200;
    public static final int hello = 0x7f000201;
    public static final int some_html = 0x7f000202;
    public static final int greeting = 0x7f000203;
    public static final int copy = 0x7f000204;
    public static final int ok = 0x7f000205;
    public static final int ok2 = 0x7f000206;
    public static final int only_in_main = 0x7f000207;
    public static final int only_in_lib1 = 0x7f000208;
    public static final int only_in_lib2 = 0x7f000209;
    public static final int only_in_lib3 = 0x7f00020a;
    public static final int in_all_libs = 0x7f00020b;
    public static final int in_lib2_and_lib3 = 0x7f00020c;
    public static final int in_lib1_and_lib3 = 0x7f00020d;
    public static final int in_main_and_lib1 = 0x7f00020e;
    public static final int interpolate = 0x7f00020f;
    public static final int app_name = 0x7f000210;
    public static final int activity_name = 0x7f000211;
    public static final int minute_singular = 0x7f000212;
    public static final int minute_plural = 0x7f000213;
    public static final int str_int = 0x7f000214;
    public static final int preference_resource_key = 0x7f000215;
    public static final int preference_resource_title = 0x7f000216;
    public static final int preference_resource_summary = 0x7f000217;
    public static final int preference_resource_default_value = 0x7f000218;
    public static final int surrounding_quotes = 0x7f000219;
    public static final int escaped_apostrophe = 0x7f00021a;
    public static final int escaped_quotes = 0x7f00021b;
    public static final int leading_and_trailing_new_lines = 0x7f00021c;
    public static final int non_breaking_space = 0x7f00021d;
    public static final int new_lines_and_tabs = 0x7f00021e;
    public static final int space = 0x7f00021f;
    public static final int say_it_with_item = 0x7f000220;
    public static final int test_menu_2 = 0x7f000221;
  }

  public static final class plurals {
    public static final int beer = 0x7f000300;
    public static final int minute = 0x7f000301;
  }

  public static final class array {
    public static final int items = 0x7f000400;
    public static final int greetings = 0x7f000401;
    public static final int alertDialogTestItems = 0x7f000402;
    public static final int emailAddressTypes = 0x7f000403;
    public static final int zero_to_four_int_array = 0x7f000404;
    public static final int empty_int_array = 0x7f000405;
    public static final int with_references_int_array = 0x7f000406;
    public static final int referenced_colors_int_array = 0x7f000407;
  }

  public static final class color {
    public static final int background = 0x7f000500;
    public static final int foreground = 0x7f000501;
    public static final int grey42 = 0x7f000502;
    public static final int black = 0x7f000503;
    public static final int blue = 0x7f000504;
    public static final int white = 0x7f000505;
    public static final int clear = 0x7f000506;
    public static final int color_with_alpha = 0x7f000507;
    public static final int android_namespaced_black = 0x7f000508;
    public static final int android_namespaced_transparent = 0x7f000509;
    public static final int android_red = 0x7f00050a;
    public static final int test_color_1 = 0x7f00050b;
    public static final int color_state_list = 0x7f00050c;
    public static final int list_separator = 0x7f00050d;
    public static final int custom_state_view_text_color = 0x7f00050e;
  }

  public static final class drawable {
    public static final int an_image = 0x7f000600;
    public static final int an_other_image = 0x7f000601;
    public static final int third_image = 0x7f000602;
    public static final int fourth_image = 0x7f000603;
    public static final int image_background = 0x7f000604;
    public static final int l0_red = 0x7f000605;
    public static final int l1_orange = 0x7f000606;
    public static final int l2_yellow = 0x7f000607;
    public static final int l3_green = 0x7f000608;
    public static final int l4_blue = 0x7f000609;
    public static final int l5_indigo = 0x7f00060a;
    public static final int l6_violet = 0x7f00060b;
    public static final int l7_white = 0x7f00060c;
    public static final int rainbow = 0x7f00060d;
    public static final int state_drawable = 0x7f00060e;
    public static final int nine_patch_drawable = 0x7f00060f;
    public static final int drawable_with_nine_patch = 0x7f000610;
    public static final int robolectric = 0x7f000611;
    public static final int vector = 0x7f000612;
  }

  public static final class layout {
    public static final int activity_list_item = 0x7f000700;
    public static final int custom_layout = 0x7f000701;
    public static final int custom_layout2 = 0x7f000702;
    public static final int custom_layout3 = 0x7f000703;
    public static final int custom_layout4 = 0x7f000704;
    public static final int different_screen_sizes = 0x7f000705;
    public static final int edit_text = 0x7f000706;
    public static final int fragment = 0x7f000707;
    public static final int fragment_activity = 0x7f000708;
    public static final int fragment_contents = 0x7f000709;
    public static final int included_layout_parent = 0x7f00070a;
    public static final int included_linear_layout = 0x7f00070b;
    public static final int inner_merge = 0x7f00070c;
    public static final int lam_inner = 0x7f00070d;
    public static final int lam_outer = 0x7f00070e;
    public static final int main = 0x7f00070f;
    public static final int mapview = 0x7f000710;
    public static final int media = 0x7f000711;
    public static final int multi_orientation = 0x7f000712;
    public static final int outer = 0x7f000713;
    public static final int override_include = 0x7f000714;
    public static final int request_focus = 0x7f000715;
    public static final int request_focus_with_two_edit_texts = 0x7f000716;
    public static final int snippet = 0x7f000717;
    public static final int styles_button_layout = 0x7f000718;
    public static final int tab_activity = 0x7f000719;
    public static final int text_views = 0x7f00071a;
    public static final int text_views_hints = 0x7f00071b;
    public static final int toplevel_merge = 0x7f00071c;
    public static final int webview_holder = 0x7f00071d;
    public static final int with_invalid_onclick = 0x7f00071e;
    public static final int styles_button_with_style_layout = 0x7f00071f;
    public static final int custom_title = 0x7f000720;
    public static final int remote_views = 0x7f000721;
    public static final int main_layout = 0x7f000722;
    public static final int activity_main = 0x7f000723;
    public static final int activity_main_1 = 0x7f000724;
    public static final int ordinal_scrollbar = 0x7f000725;
    public static final int custom_layout5 = 0x7f000726;
    public static final int custom_layout6 = 0x7f000727;
  }

  public static final class anim {
    public static final int test_anim_1 = 0x7f000800;
    public static final int animation_list = 0x7f000801;
  }

  public static final class animator {
    public static final int spinning = 0x7f000900;
    public static final int fade = 0x7f000901;
  }

  public static final class raw {
    public static final int raw_resource = 0x7f000a00;
    public static final int raw_no_ext = 0x7f000a01;
    public static final int lib_raw_resource = 0x7f000a02;
    public static final int lib_raw_resource_from_2 = 0x7f000a03;
    public static final int lib_raw_resource_from_3 = 0x7f000a04;
  }

  public static final class attr {
    public static final int isSugary = 0x7f000b00;
    public static final int itemType = 0x7f000b01;
    public static final int scrollBars = 0x7f000b02;
    public static final int gravity = 0x7f000b03;
    public static final int keycode = 0x7f000b04;
    public static final int aspectRatio = 0x7f000b05;
    public static final int aspectRatioEnabled = 0x7f000b06;
    public static final int items = 0x7f000b07;
    public static final int logoHeight = 0x7f000b08;
    public static final int quitKeyCombo = 0x7f000b09;
    public static final int responses = 0x7f000b0a;
    public static final int animalStyle = 0x7f000b0b;
    public static final int stateFoo = 0x7f000b0c;
    public static final int someLayoutOne = 0x7f000b0d;
    public static final int someLayoutTwo = 0x7f000b0e;
  }

  public static final class menu {
    public static final int test = 0x7f000c00;
    public static final int test_withchilds = 0x7f000c01;
    public static final int action_menu = 0x7f000c02;
    public static final int test_withorder = 0x7f000c03;
  }

  public static final class xml {
    public static final int preferences = 0x7f000d00;
    public static final int dialog_preferences = 0x7f000d01;
  }

  public static final class styleable {
    public static final int[] CustomView = {
        attr.itemType,
        attr.scrollBars,
        attr.keycode,
        attr.aspectRatio,
        attr.aspectRatioEnabled,
        attr.quitKeyCombo,
        attr.animalStyle
    };

    public static final int CustomView_itemType = 0;
    public static final int CustomView_scrollBars = 1;
    public static final int CustomView_keycode = 2;
    public static final int CustomView_aspectRatio = 3;
    public static final int CustomView_aspectRatioEnabled = 4;
    public static final int CustomView_quitKeyCombo = 5;
    public static final int CustomView_animalStyle = 6;

    public static final int[] HeaderBar = {id.textStyle2, id.textStyle3};
    public static final int HeaderBar_textStyle2 = 0;
    public static final int HeaderBar_textStyle3 = 1;
  }

  public static final class dimen {
    public static final int test_dp_dimen = 0x7f000e00;
    public static final int test_dip_dimen = 0x7f000e01;
    public static final int test_pt_dimen = 0x7f000e02;
    public static final int test_px_dimen = 0x7f000e03;
    public static final int test_sp_dimen = 0x7f000e04;
    public static final int test_in_dimen = 0x7f000e05;
    public static final int test_mm_dimen = 0x7f000e06;
  }

  public static final class integer {
    public static final int test_non_integer = 0x7f000f00;
    public static final int test_integer1 = 0x7f000f01;
    public static final int test_integer2 = 0x7f000f02;
    public static final int test_large_hex = 0x7f000f03;
    public static final int meaning_of_life = 0x7f000f04;
    public static final int loneliest_number = 0x7f000f05;
    public static final int there_can_be_only = 0x7f000f06;
    public static final int hex_int = 0x7f000f07;
    public static final int test_value_with_zero = 0x7f000f08;
    public static final int reference_to_meaning_of_life = 0x7f000f09;
    public static final int meaning_of_life_as_item = 0x7f000f0a;
    public static final int scrollbar_style_ordinal_outside_overlay = 0x7f000f0b;
  }

  public static final class bool {
    public static final int false_bool_value = 0x7f001000;
    public static final int true_bool_value = 0x7f001001;
    public static final int zero_is_false = 0x7f001002;
    public static final int integers_are_true = 0x7f001003;
    public static final int reference_to_true = 0x7f001004;
    public static final int true_as_item = 0x7f001005;
    public static final int different_resource_boolean=0x7f001006;
  }

  public static final class style {
    public static final int FancyStyle = 0x7f001100;
    public static final int Theme_Robolectric = 0x7f001101;
    public static final int Theme_AnotherTheme = 0x7f001102;
    public static final int MyCustomView = 0x7f001103;
    public static final int Widget_Robolectric_Button = 0x7f001104;
    public static final int Widget_AnotherTheme_Button = 0x7f001105;
    public static final int Sized = 0x7f001106;
    public static final int Gastropod = 0x7f001107;
    public static final int Theme_ThirdTheme = 0x7f001108;
    public static final int MyBlackTheme = 0x7f001109;
    public static final int MyBlueTheme = 0x7f00110a;
    public static final int IndirectButtonStyle = 0x7f00110b;
  }

  public static final class fraction {
    public static final int half = 0x7f001200;
    public static final int half_of_parent = 0x7f001201;
    public static final int quarter_as_item = 0x7f001202;
    public static final int quarter_of_parent_as_item = 0x7f001203;
    public static final int fifth = 0x7f001204;
    public static final int fifth_as_reference = 0x7f001205;
    public static final int fifth_of_parent = 0x7f001206;
    public static final int fifth_of_parent_as_reference = 0x7f001207;
  }

  public static final class mipmap {
    public static final int robolectric = 0x7f001300;
  }
}
