package org.robolectric.simulator.gradle

import com.android.build.gradle.AppExtension
import java.io.File
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.JavaExec
import org.gradle.api.tasks.testing.Test
import org.robolectric.simulator.gradle.generated.Version

class SimulatorPlugin : Plugin<Project> {
  override fun apply(project: Project) {
    val androidExtension = getAndroidExtension(project)
    if (androidExtension == null) {
      return
    }

    project.afterEvaluate {
      project.tasks.register("simulate", JavaExec::class.java) {
        group = "simulation"
        description = "Runs the Robolectric simulator"
        configureTask(project, this)
      }
    }
  }

  private fun getAndroidExtension(project: Project) =
    project.extensions.findByType(AppExtension::class.java)

  private fun configureTask(project: Project, task: JavaExec) {

    val testTaskName = "testDebugUnitTest"
    val testTask = project.tasks.findByName(testTaskName) as? Test
    val buildDir = project.buildDir
    // This is the name of the resource APK file generated by AGP for Robolectric tests.
    // TODO(hoisie): derive this path from the Android plugin.
    val resourceApkFile =
      File(buildDir, "intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_")

    if (testTask == null) {
      throw IllegalStateException("Missing testDebugUntTest task")
    }

    val simulator =
      project.configurations
        .detachedConfiguration(
          project.dependencies.create("org.robolectric:simulator:${Version.VERSION}")
        )
        .resolve()

    task.apply {
      classpath = testTask.classpath + project.files(simulator)
      jvmArgs = testTask.jvmArgs
      mainClass.set("org.robolectric.simulator.SimulatorMain")
      args = listOf(resourceApkFile.absolutePath)
      dependsOn(testTaskName, "assembleDebug")
      standardOutput = System.out
      errorOutput = System.err
    }
  }
}
