name: Build Native Runtime

env:
  CXX: clang++
  CC: clang

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build_native_runtime:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 11.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Cache ICU build output
        id: cache-icu
        uses: actions/cache@v2
        with:
          path: ~/icu-bin
          key: ${{ runner.os }}-icu-${{ hashFiles('nativeruntime/external/icu/**') }}

      - name: Build ICU for MacOS
        if: runner.os =='macOS' && steps.cache-icu.outputs.cache-hit != 'true'
        run: |
          cd nativeruntime/external/icu/icu4c/source
          ./runConfigureICU MacOSX --enable-static --prefix=$HOME/icu-bin
          make -j4
          make install

      - name: Build ICU for Linux
        if: runner.os == 'Linux' && steps.cache-icu.outputs.cache-hit != 'true'
        run: |
          export CFLAGS="$CFLAGS -fPIC"
          export CXXFLAGS="$CXXFLAGS -fPIC"
          cd nativeruntime/external/icu/icu4c/source
          ./runConfigureICU Linux --enable-static --prefix=$HOME/icu-bin
          make -j4
          make install

      - name: Run CMake
        run: |
          mkdir build
          cd build
          ICU_ROOT_DIR=$HOME/icu-bin cmake -B . -S ../nativeruntime/cpp -DCMAKE_C_FLAGS=-Os -DCMAKE_CXX_FLAGS=-Os
          make

      - name: Rename libnativeruntime for Linux
        if: runner.os == 'Linux'
        run: |
          mv build/libnativeruntime.so build/librobolectric-nativeruntime-linux-x86_64.so

      - name: Rename libnativeruntime for Linux
        if: runner.os == 'macOS'
        run: |
          mv build/libnativeruntime.dylib build/librobolectric-nativeruntime-mac-x86_64.dylib

      - name: Upload libnativeruntime for Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: librobolectric-nativeruntime-linux-x86_64.so
          path: |
            build/librobolectric-nativeruntime-linux-x86_64.so
            build/*.dylib

      - name: Upload libnativeruntime for Linux
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: librobolectric-nativeruntime-mac-x86_64.dylib
          path: |
            build/librobolectric-nativeruntime-mac-x86_64.dylib
