name: Check Code Style

on:
  push:
    branches: [ master, 'robolectric-*.x' ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master, google ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check_code_style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Check Java and Kotlin Formatting
        run: ./gradlew spotlessCheck

      - name: Check Kotlin Quality
        run: ./gradlew detekt

      - name: Check Android Lint
        run: ./gradlew lint --continue
