name: Gradle Tasks Validation

on:
  push:
    branches: [ master, 'robolectric-*.x' ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master, google ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run_aggregateDocs:
    name: Aggregate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run :aggregateDocs
        # Disable parallel as a workaround for Gradle 9's concurrent model.
        run: ./gradlew :aggregateDocs --no-parallel

      - name: Upload docs
        uses: actions/upload-artifact@v7
        with:
          name: robolectric-javadoc-artifacts
          path: build/docs

  run_javadocJar:
    name: Javadoc Jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run javadocJar
        run: ./gradlew javadocJar

  run_instrumentAll:
    name: Instrument All
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run :preinstrumented:instrumentAll
        run: ./gradlew :preinstrumented:instrumentAll

      - name: Run :preinstrumented:instrumentAll with SDK 36
        run: PREINSTRUMENTED_SDK_VERSIONS=36 ./gradlew :preinstrumented:instrumentAll

      - name: Run :preinstrumented:publishToMavenLocal with SDK 36
        run: PREINSTRUMENTED_SDK_VERSIONS=36 PUBLISH_PREINSTRUMENTED_JARS=true ./gradlew :preinstrumented:publishToMavenLocal

  run_publishToMavenLocal:
    name: Publish to Maven local
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Publish to Maven local
        run: ./gradlew publishToMavenLocal
