name: Tests

on:
  push:
    branches: [ master, 'robolectric-*.x', 'google' ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  cache-version: v4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        env:
          SKIP_ERRORPRONE: true
          SKIP_JAVADOC: true
        run: ./gradlew assemble testClasses --stacktrace

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        api-versions: [
          '23,24,25',
          '26,27,28',
          '29,30,31',
          '32,33,34',
          '35,36,37'
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run unit tests
        env:
          SKIP_ERRORPRONE: true
          SKIP_JAVADOC: true
        run: >
          ./gradlew test
          --stacktrace --continue
          -Drobolectric.enabledSdks=${{ matrix.api-versions }}
          -Drobolectric.alwaysIncludeVariantMarkersInTestName=true
          -x :integration_tests:nativegraphics:test
          -x :integration_tests:roborazzi:test

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test_results_${{ matrix.api-versions }}
          path: '**/build/test-results/**/TEST-*.xml'

  instrumentation-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: build

    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        api-level: [ 30, 36 ]

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: false

      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Accept Android SDK licences
        run: yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses > /dev/null

      - name: Managed device cache
        uses: actions/cache@v6
        with:
          path: ~/.android/avd/gradle-managed
          key: gmd-ubuntu-${{ matrix.api-level }}-${{ env.cache-version }}

      - name: Run device tests
        env:
          SKIP_ERRORPRONE: true
          SKIP_JAVADOC: true
        run: ./gradlew -Pandroid.sdk.channel=3 nexusOneApi${{ matrix.api-level }}DebugAndroidTest --stacktrace

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results-${{ matrix.api-level }}
          path: |
            **/build/reports/androidTests/**
            **/build/outputs/androidTest-results/**

  publish-to-snapshots:
    runs-on: ubuntu-latest
    env:
      SONATYPE_LOGIN: ${{ secrets.SONATYPE_LOGIN }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    needs: unit-tests
    if: github.repository == 'robolectric/robolectric' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Publish
        run: ./gradlew publish --stacktrace
